"""empty message

Revision ID: 052612d01335
Revises: c5a7d85cdd18
Create Date: 2023-06-25 21:37:29.192690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '052612d01335'
down_revision = 'c5a7d85cdd18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    # ### end Alembic commands ###
