"""empty message

Revision ID: 52cd5f225c92
Revises: 052612d01335
Create Date: 2023-07-04 16:47:52.508756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52cd5f225c92'
down_revision = '052612d01335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column("users", sa.Column('email', sa.String(), nullable=False))
    op.create_unique_constraint("email", "users", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_constraint("email", "users", type_='unique')
    op.drop_column("users", "email")

    # ### end Alembic commands ###
